apiVersion: v1
kind: ConfigMap
metadata:
  name: polyhunter-config
  namespace: polyhunter-stage1
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"

  NEXT_PUBLIC_NETWORK: "polygon"
  NEXT_PUBLIC_CHAIN_ID: "137"
  NEXT_PUBLIC_RPC_URL: "https://polygon-rpc.com"
  NEXT_PUBLIC_PROXY_FACTORY_ADDRESS: "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_TREASURY_ADDRESS: "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_EXECUTOR_ADDRESS: "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_USDC_ADDRESS: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
  NEXT_PUBLIC_CTF_ADDRESS: "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045"

  DATABASE_URL: "postgresql://polyhunter:polyhunter@postgres:5432/polyhunter?schema=public"
  REDIS_URL: "redis://redis:6379"
  SUPERVISOR_REDIS_URL: "redis://redis:6379"
  KAFKA_BROKERS: "redpanda:9092"

  COPY_TRADING_API_URL: "http://frontend:3000"
  COPY_TRADING_RPC_URL: "https://polygon-rpc.com"
  COPY_TRADING_WS_FILTER_BY_ADDRESS: "true"
  COPY_TRADING_DRY_RUN: "true"
  ENABLE_REAL_TRADING: "false"
  COPY_TRADING_GLOBAL_ORDERS_PER_MIN: "300"
  COPY_TRADING_USER_ORDERS_PER_MIN: "60"
  COPY_TRADING_PRICE_TTL_MS: "5000"
  COPY_TRADING_PREFLIGHT_CACHE_TTL_MS: "2000"
  COPY_TRADING_QUOTE_CACHE_MAX_ENTRIES: "500"
  COPY_TRADING_PREFLIGHT_CACHE_MAX_ENTRIES: "1000"
  COPY_TRADING_LOCK_TTL_MS: "300000"
