apiVersion: v1
kind: Secret
metadata:
  name: polyhunter-secrets
  namespace: polyhunter-stage1
type: Opaque
stringData:
  NEXTAUTH_SECRET: "replace-with-long-random-secret"
  TRADING_PRIVATE_KEY: "0xREPLACE_ME"
  TRADING_MNEMONIC: "replace me with 12 words"
  POLY_API_KEY: ""
  POLY_API_SECRET: ""
  POLY_API_PASSPHRASE: ""
